families:
  jeff_and_trisha:
   - Colbie
  necia_and_nick:
   - Hallie
   - Tucker
   - Makenna
   - Mailey
   - Bennett
  dustin_and_jen:
   - Stacia
   - Crew
   - Sophie
  cody_and_heather:
   - Tatum
   - Suzie
   - Walter
   - Lionel
  cass_and_jamie:
   - Athena
   - Presley
history:
  2022:
    Colbie: Walter
    Hallie: Tatum
    Tucker: Sophie
    Makenna: Stacia
    Mailey: Suzie
    Bennett: Presley
    Stacia: Hallie
    Crew: Mailey
    Sophie: Lionel
    Tatum: Tucker
    Suzie: Makenna
    Walter: Bennett
    Lionel: Athena
    Presley: Colbie
    Athena: Crew
  2021:
    Brody: Sophie
    Colbie: Stacia
    Hallie: Lionel
    Tucker: Tatum
    Makenna: Walter
    Mailey: Colbie
    Bennett: Brody
    Stacia: Bennett
    Crew: Tucker
    Sophie: Suzie
    Tatum: Makenna
    Suzie: Hallie
    Walter: Crew
    Lionel: Mailey
  2020:
    Brody: Lionel
    Colbie: Makenna
    Hallie: Sophie
    Tucker: Suzie
    Makenna: Brody
    Mailey: Crew
    Bennett: Tatum
    Stacia: Mailey
    Crew: Bennett
    Sophie: Walter
    Tatum: Hallie
    Suzie: Tucker
    Walter: Stacia
    Lionel: Colbie
  2019:
    Chaz: Sophie
    Brody: Tatum
    Colbie: Carson
    Carson: Lionel
    Hallie: Suzie
    Tucker: Walter
    Stacia: Colbie
    Crew: Hallie
    Sophie: Brody
    Tatum: Chaz
    Suzie: Crew
    Walter: Tucker
    Lionel: Stacia
  2018:
    JT: Tucker
    Chaz: Stacia
    Brody: Walter
    Colbie: Hallie
    Carson: Crew
    Hallie: Brody
    Tucker: Lionel
    Stacia: Chaz
    Crew: Suzie
    Sophie: Tatum
    Tatum: JT
    Suzie: Colbie
    Walter: Carson
    Lionel: Sophie
  2017:
    JT: Crew
    Chaz: Carson
    Brody: Tucker
    Colbie: Walter
    Carson: Brody
    Hallie: Colbie
    Tucker: Tatum
    Stacia: Lionel
    Crew: JT
    Sophie: Suzie
    Tatum: Stacia
    Suzie: Chaz
    Walter: Sophie
    Lionel: Hallie
  2016:
    JT: Sophie
    Chaz: Suzie
    Brody: Stacia
    Colbie: Tatum
    Carson: Chaz
    Hallie: Lionel
    Tucker: Crew
    Stacia: Carson
    Crew: Hallie
    Sophie: Walter
    Tatum: Tucker
    Suzie: Brody
    Walter: Colbie
    Lionel: JT
  2015:
    JT: Walter
    Chaz: Stacia
    Brody: Crew
    Colbie: Suzie
    Carson: Sophie
    Hallie: JT
    Tucker: Colbie
    Stacia: Tucker
    Crew: Lionel
    Sophie: Tatum
    Tatum: Hallie
    Suzie: Carson
    Walter: Chaz
    Lionel: Brody
  2014:
    JT: Crew
    Chaz: Tatum
    Brody: Hallie
    Colbie: Tucker
    Carson: Brody
    Hallie: Colbie
    Tucker: Walter
    Stacia: Chaz
    Crew: Suzie
    Sophie: JT
    Tatum: Stacia
    Suzie: Sophie
    Walter: Carson
  2013:
    JT: Stacia
    Chaz: Walter
    Brody: Carson
    Colbie: Sophie
    Carson: Chaz
    Hallie: Suzie
    Tucker: JT
    Stacia: Brody
    Crew: Tatum
    Sophie: Tucker
    Tatum: Crew
    Suzie: Colbie
    Walter: Hallie
  2012:
    JT: Tucker
    Chaz: Stacia
    Brody: Suzie
    Colbie: Crew
    Carson: Tatum
    Hallie: Sophie
    Tucker: Brody
    Stacia: Hallie
    Crew: Carson
    Sophie: Colbie
    Tatum: JT
    Suzie: Chaz
  2011:
    JT: Suzie
    Chaz: Hallie
    Brody: Tatum
    Colbie: Carson
    Carson: Crew
    Hallie: Chaz
    Tucker: Stacia
    Stacia: JT
    Crew: Colbie
    Tatum: Tucker
    Suzie: Brody
